/* Generated by Report Generator v4.2 (R2015b) */
var gHomeSys = "Push_Button_EdgeDetection";
var gNumSys = 19;
var gFrameID = {
"frameset_main":"Push_Button_EdgeDetection_slwebview_main_frameset",
"explorer":"Push_Button_EdgeDetection_slwebview_explorer",
"frameset_model":"Push_Button_EdgeDetection_slwebview_frame",
"model":"Push_Button_EdgeDetection_slwebview_model",
"web":"Push_Button_EdgeDetection_slwebview_web"};
var gIDMap = {
"Push_Button_EdgeDetection":{"target":"slwebview_1.svg","thumb":"slwebview_1_tb.png"},
"Push_Button_EdgeDetection:41":{"target":"slwebview_2.svg","thumb":"slwebview_2_tb.png"},
"Push_Button_EdgeDetection:27":{"target":"slwebview_3.svg","thumb":"slwebview_3_tb.png"},
"Push_Button_EdgeDetection:68":{"target":"slwebview_4.svg","thumb":"slwebview_4_tb.png"},
"Push_Button_EdgeDetection:69":{"target":"slwebview_5.svg","thumb":"slwebview_5_tb.png"},
"Push_Button_EdgeDetection:80":{"target":"slwebview_6.svg","thumb":"slwebview_6_tb.png"},
"Push_Button_EdgeDetection:81":{"target":"slwebview_7.svg","thumb":"slwebview_7_tb.png"},
"Push_Button_EdgeDetection:82":{"target":"slwebview_8.svg","thumb":"slwebview_8_tb.png"},
"Push_Button_EdgeDetection:83":{"target":"slwebview_9.svg","thumb":"slwebview_9_tb.png"},
"Push_Button_EdgeDetection:70":{"target":"slwebview_10.svg","thumb":"slwebview_10_tb.png"},
"Push_Button_EdgeDetection:73":{"target":"slwebview_11.svg","thumb":"slwebview_11_tb.png"},
"Push_Button_EdgeDetection:74":{"target":"slwebview_12.svg","thumb":"slwebview_12_tb.png"},
"Push_Button_EdgeDetection:75":{"target":"slwebview_13.svg","thumb":"slwebview_13_tb.png"},
"Push_Button_EdgeDetection:76":{"target":"slwebview_14.svg","thumb":"slwebview_14_tb.png"},
"Push_Button_EdgeDetection:77":{"target":"slwebview_15.svg","thumb":"slwebview_15_tb.png"},
"Push_Button_EdgeDetection:78":{"target":"slwebview_16.svg","thumb":"slwebview_16_tb.png"},
"Push_Button_EdgeDetection:79":{"target":"slwebview_17.svg","thumb":"slwebview_17_tb.png"},
"Push_Button_EdgeDetection:27:2":{"target":"slwebview_18.svg","thumb":"slwebview_18_tb.png"},
"Push_Button_EdgeDetection:27:3":{"target":"slwebview_19.svg","thumb":"slwebview_19_tb.png"}};

var gSLFcnId2SubsysId = {};